### ISSUE TITLE
A mismatch between readme.md and the actual CLI interface

### ISSUE THREAD

**Issue by TobiSan5** [pyscript/pyscript-cli#131] opened 2023-08-23 08:44 UTC
I pip installed pyscript into a python 3.11 environment, and got version 0.2.5 of pyscript-cli. The documentation in this repository's readme.md does not match the CLI interface. In the documentation, there is the option `--wrap`, while the CLI has the command `wrap`. Furthermore, there is no such command `run` in the CLI. Could this be because I am on Windows, which doesn't support the server being used?

**Comment by madhur-tandon** [comment] 2023-08-23 15:11
Hi @TobiSan5
This is because it's been a while since a new version has been released for the CLI.
For now, you can clone this repository and install the local version from there, which should match with the README.

But, we will soon be releasing a new version that should match the current state of the repository.

**Comment by FabioRosado** [comment] 2024-02-28 13:56
Hello we are planning to release a new CLI version soon - probably next week. I'm going to close this issue since it will fix the issue reported here, but please feel free to comment or re-open the issue is needed

**Closed by FabioRosado** 2024-02-28 13:56 UTC
